# Example returning a JSON data type
# This workflow uses fromJSON to convert environment variables from a string to a Boolean or integer.
on: push
env: 
  continue: true
  time: 3
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: ${{ fromJSON(env.continue) }}
        timeout-minutes: ${{ fromJSON(env.time) }}
        run: echo 'job1 finished'
