name: workflow-commands
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::blue'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
  job3:
    runs-on: ubuntu-latest
    steps:
    -name: add a system path
    id: add-sys-path
    run: |
      echo "$HOME/.local/bin" >> $GITHUB_PATH
